<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PURNA02-W7" name="Test" tests="4" failures="1" timestamp="4 Nov 2018 19:39:36 GMT" time="33.859" errors="0">
  <testcase name="CheckImage" time="0.069" classname="functional.VerifyHomeImageTest"/>
  <testcase name="verifyExistingVeterinarians" time="0.486" classname="functional.VerifyExistingVeterinariansTest"/>
  <testcase name="verifyAddNewOwnderAndPet" time="3.628" classname="functional.verifyAddNewOwnerAndPetTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at pages.FindOwnersPage.verifyNewlyAddedOwnerAndPet(FindOwnersPage.java:61)
	at functional.verifyAddNewOwnerAndPetTest.verifyAddNewOwnderAndPet(verifyAddNewOwnerAndPetTest.java:58)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddNewOwnderAndPet -->
  <testcase name="verifyAddNewOwnerTab" time="1.489" classname="functional.VerifyExistingOwnersTest"/>
</testsuite> <!-- Test -->
